[language-server.typos]
command = "typos-lsp"
config.diagnosticSeverity = "Warning"

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "markdown"
language-servers = ["typos", "harper-ls", "marksman"]

[[language]]
name = "typst"
language-servers = ["tinymist", "typos"]
formatter = ["typstyle"]

[language-server.tinymist.config]
exportPdf = "onSave"
rootPath = "/Users/study/research-project/paper"
typstExtraArgs = ["entrypoint.typ"]
outputPath = "$root/build/paper-debug.pdf" 

[language-server.harper-ls.config.harper-ls.linters]
SpelledNumbers = true
BoringWords = false
